### ISSUE TITLE
Validate description for new company

### ISSUE THREAD

**Issue by mdelreal** [rendon/accounty#1]
Leaving the description empty for a new company results in an error (http 500) while attempting to save the new company.

OS: ubuntu 12 
Browser: Chrome 39

**Comment by mdelreal** [comment]
Before submit:
![image](https://cloud.githubusercontent.com/assets/5913835/6833071/f2ed3302-d2ef-11e4-9ad6-05a720e530fa.png)


After submit:

![image](https://cloud.githubusercontent.com/assets/5913835/6833086/094b48d2-d2f0-11e4-976e-7f32ced1e2fb.png)

**Comment by rendon** [comment]
:). It seems that I need to add more tests for those corner cases.

**Comment by rendon** [comment]
Fixed with 5fbb964c404a30d99b7b4a931b18712454adfbe3.
